Repository MapServer/MapServer, pull requests merged in 2021-04, with the labels that each got.

#6282 maporacle - using dynamically-allocated buffers for constructing SQL queries
  maporaclespatial.c
  msautotest/msoracle/README.md
  msautotest/msoracle/docker-compose.yaml
  msautotest/msoracle/expected/oracle.png
  msautotest/msoracle/oracle.map
  msautotest/msoracle/run_test.py
  msautotest/msoracle/sample-data.sql
  msautotest/msoracle/tnsnames.ora
Labels: Review required

#6295 Fix resource leak and pointObj initialization errors.
  mapdraw.c
  mapfile.c
  mapgml.c
  maplabel.c
  mapobject.c
  mapows.c
  mappostgis.cpp
  mapprimitive.c
  mapproject.c
  mapsmoothing.c
  maptemplate.c
  mapwcs.cpp
  mapwcs20.cpp
  mapwfs.cpp
  mapwmslayer.c
Labels: backport branch-7-6

#6288 Only select requested fields for all WFS query types
  maplayer.c
  mapquery.c
Labels: Performance, WFS Server

#6297 Fixes for a couple of things I ran into when doing an upgrade on app
  mapdraw.c
  mapfile.c
  mapraster.c
Labels: backport branch-7-6

#6304 WIP: Use CPLSetConfigOption/CPLGetConfigOption for some CGI/FastCGI-related env vars.
  maphttp.c
  mapserv.c
  mapserv.h
  mapservutil.c
Labels: Work in progress

#6306 Fix most of remaining Coverity scan warnings with high priority
  mapcontext.c
  mapcpl.c
  mapfile.c
  mapogcsld.c
  mapogcsos.c
  mapogr.cpp
  mapstring.cpp
  mapwfs.cpp
Labels: backport branch-7-6
