Repository MapServer/MapServer, pull requests merged in 2022-09, with the labels that each got.

#6603 Check if a LAYER has a NAME before accessing the property
  mapwms.cpp
Labels: backport branch-8-0

#6602 Fix for #6601 - ensure a valid WHERE clause is created in all cases
  mappostgis.cpp
  msautotest/wxs/expected/wms_get_map_polygon_postgis_boxtoken.png
  msautotest/wxs/wms_postgis_boxtoken.map
Labels: backport branch-8-0

#6606 update tests for PHP 8.1.10 release
  .travis.yml
Labels: Work in progress, backport branch-8-0

#6615 update security policy to mention 8.0 release
  SECURITY.md
Labels: backport branch-8-0

#6617 Set layer startindex for paging in OGC Features API
  mapogcapi.cpp
Labels: backport branch-8-0

#6616 Redact password= content in msError() and msDebug() messages
  mapdebug.c
  maperror.c
  maperror.h
  mappostgis.cpp
Labels: backport branch-7-6, backport branch-8-0

#6625 correct CONFIG url message
  mapfile.c
  mapserv-config.cpp
  msautotest/config/expected/missing_conf.txt
Labels: backport branch-8-0

#6634 shapeObjTest.php: adjust expected result ...
  msautotest/php/shapeObjTest.php
Labels: backport branch-8-0

#6633 msLoadConfig(): fix memory leak if configuration file cannot be open
  mapserv-config.cpp
Labels: backport branch-8-0
