Repository MapServer/MapServer, pull requests merged in 2023-01, with the labels that each got.

#6780 Fix information disclosure and denial of service related to CONTEXT= loading
  .github/workflows/start.sh
  mapcontext.c
  mapows.h
  mapserver.h
  mapservutil.c
  msautotest/etc/mapserv.conf
  msautotest/wxs/expected/ows_context_caps.xml
  msautotest/wxs/ows_context.map
  msautotest/wxs/ows_context.xml
Labels: backport branch-7-6, backport branch-8-0

#6788 doc: correct MS_SHP to MS_SHAPEFILE
  mapscript/swiginc/shapefile.i
  mapscript/tcl/mapscript_wrap.html
Labels: backport branch-8-0

#6796 update copyright year in README
  INSTALL
  README.md
Labels: backport branch-7-6, backport branch-8-0

#6793 Set Boolean field type with PostGIS driver when using gml_types auto
  mappostgis.cpp
  msautotest/create_postgis_test_data.sh
  msautotest/wxs/expected/wfs_autotypes10_postgis.xml
  msautotest/wxs/expected/wfs_autotypes11_postgis.xml
  msautotest/wxs/expected/wfs_autotypes20_postgis.xml
  msautotest/wxs/expected/wfs_getfeaturetypes10_postgis.xml
  msautotest/wxs/expected/wfs_getfeaturetypes11_postgis.xml
  msautotest/wxs/expected/wfs_getfeaturetypes20_postgis.xml
  msautotest/wxs/wfs_autotypes_postgis.map
Labels: backport branch-8-0

#6799 update markdown for README and LICENSE
  LICENSE.md
  README.md
Labels: backport branch-8-0

#6794 Add Proj and GDAL versions to MapServer version output
  maperror.c
Labels: backport branch-8-0

#6804 Small changes missed in the initial 8.0 release.
  mapfile.c
  mapservutil.c
Labels: backport branch-8-0

#6784 Update MS SQL Server connection error logging
  maperror.c
  mapmssql2008.c
Labels: Review required, backport branch-8-0

#6759 Add WIN32 flag to SWIG csharp command line, prevent classObj_drawLegendIcon to cause crash (#6758)
  mapscript/csharp/CMakeLists.txt
  mapscript/swiginc/class.i
Labels: backport branch-8-0

#6790 ZIP OGR output: use CPLAddFileInZip() to be able to generate SOZip-enabled files
  mapogroutput.cpp
Labels: Work in progress

#6731 Allow NULL shapes to be returned in WFS GetFeature requests
  mapogroutput.cpp
  mapproject.c
  mapquery.c
  msautotest/mssql/expected/null_and_point.json
  msautotest/mssql/expected/null_and_point_reprojected.json
  msautotest/mssql/wfs_ogr_export.map
Labels: Review required, backport branch-8-0

#6786 Optimise WMS requests by ignoring any fields that won't be used
  maplayer.c
Labels: Review required
