Repository MapServer/MapServer, pull requests merged in 2024-07, with the labels that each got.

#7097 add PHP 8.3 to test matrix
  .github/workflows/build-mapscript-php.yml
  ci/build.sh
  msautotest/php/run_test.sh
Labels: MapScript-PHP, backport branch-8-2, CI Testing

#7096 Use EPSGTreatsAsLatLong and EPSGTreatsAsNorthingEasting to determine inverted axis
  scripts/mapaxisorder/create_mapaxisorder_csv.py
  scripts/mapaxisorder/mapaxisorder.csv
  scripts/mapaxisorder/mapaxisorder.sh
  src/mapaxisorder.h
Labels: backport branch-8-2

#7102 Implement Windows, Linux, and OSX CI builds
  .github/workflows/build-mapscript-php.yml
  .github/workflows/build-mapscript-python.yml
  .github/workflows/conda.yml
  .github/workflows/start.sh
  CMakeLists.txt
  ci/conda/cmake.sh
  ci/conda/environment.yml
  ci/ubuntu/build.sh
  ci/ubuntu/setup.sh
  src/mapcompositingfilter.c
Labels: CI Testing

#7104 handle PHP out of source builds
  src/mapscript/phpng/CMakeLists.txt
Labels: backport branch-8-2

#7113 Fix build -DWITH_OGCAPI=1 -DWITH_WFS=0
  src/mapgml.c
  src/mapogcapi.cpp
  src/mapows.h
  src/mapwfs.cpp
  src/mapwfs11.cpp
  src/mapwfs20.c
Labels: backport branch-8-2

#7121 msProcessProjection(): strip epsgaxis= MapServer specific parameter that confuses PROJ < 9.5.0
  src/mapproject.c
Labels: backport branch-8-2

#7118 tostring() expression function: validate format string, and make sure buffer is large enough
  CMakeLists.txt
  src/mapparser.c
  src/mapparser.y
  src/mapserver.h
  src/mapstring.cpp
  tests/unit/test.cpp
Labels: backport branch-8-2

#7106 Update security policy to mention 8.2 release
  SECURITY.md
Labels: backport branch-8-0, backport branch-8-2

#7111 Fix CLUSTER layers to return EXTENT
  msautotest/misc/cluster.map
  msautotest/misc/expected/cluster.png
  msautotest/misc/expected/wms_cluster_cap.xml
  msautotest/misc/expected/wms_cluster_cap_latestversion.xml
  msautotest/misc/expected/wms_get_map_cluster.png
  src/mapcluster.c
  src/mappostgis.cpp
Labels: backport branch-8-2

#7115 Fix style scale factor inheritance
  msautotest/misc/data/styleitem_style.csv
  msautotest/misc/expected/scale_factor_inheritance.png
  msautotest/misc/scale_factor_inheritance.map
  src/mapdraw.c
  src/maplayer.c
  src/mapserver.h
Labels: backport branch-8-2
