Repository MapServer/MapServer, pull requests merged in 2024-08, with the labels that each got.

#7131 allow explicit override of MapScript output folder via CMake variable
  src/mapscript/python/CMakeLists.txt
Labels: Build Problems, backport branch-8-2

#7132 Increase CMake minimum version to 3.16, which matches GDAL 3.9+
  CMakeLists.txt
  src/mapscript/csharp/CMakeLists.txt
  src/mapscript/phpng/CMakeLists.txt
Labels: Build Problems

#7140 fix proj epsgaxis= stripping to also work for +epsgaxis=
  src/mapproject.c
Labels: backport branch-8-2

#7141 fix stripping epsgaxis= before importing OSR projection
  msautotest/wxs/expected/wcs11_post_getcov_grd_4326.dat
  msautotest/wxs/expected/wcs_20_getcov_outputcrs.tif
  msautotest/wxs/expected/wcs_20_getcov_reproj.tif
  msautotest/wxs/expected/wcs_20_getcov_reproj_scaling_resolution_trim_both.tif
  msautotest/wxs/expected/wcs_20_getcov_reproj_scaling_size_trim_both.tif
  msautotest/wxs/expected/wcs_20_getcov_subsettingcrs.tif
  msautotest/wxs/expected/wcs_20_post_getcov_reproj.tif
  msautotest/wxs/expected/wcs_20_post_getcov_reproj_scaling_resolution_trim_both.tif
  msautotest/wxs/expected/wcs_20_post_getcov_reproj_scaling_size_trim_both.tif
  msautotest/wxs/expected/wcs_20_post_getcov_subsettingcrs_outputcrs.tif
  msautotest/wxs/expected/wcs_getcov_grd_11_4326.dat
  msautotest/wxs/expected/wcs_mask_20_getcov_reproj.tif
  msautotest/wxs/expected/wcs_mask_20_getcov_reproj_scaling_resolution_trim_both.tif
  msautotest/wxs/expected/wcs_mask_20_getcov_reproj_scaling_size_trim_both.tif
  msautotest/wxs/expected/wcs_mask_getcov_grd_11_4326.dat
  msautotest/wxs/expected/wcs_netcdf_input_output_wcs20_get_coverage.nc
  msautotest/wxs/expected/wfs2_query_cache.json
  msautotest/wxs/expected/wfs2_query_cache_no_default_extent.json
  msautotest/wxs/expected/wms_raster_query.json
  src/mapgdal.cpp
Labels: backport branch-8-2

#7144 Fix compilation error against FreeType 2.13.3
  src/mapagg.cpp
  src/renderers/agg/src/agg_font_freetype.cpp
Labels: backport branch-8-2
