Repository MapServer/MapServer, pull requests merged in 2025-09, with the labels that each got.

#7331 Update SDTS test to use SXF driver
  msautotest/wxs/expected/wfs_ogr_drv_nocreatedatasource_caps.xml
  msautotest/wxs/wfs_ogr_drv_nocreatedatasource.map
Labels: backport branch-8-4

#7329 msautotest Python GDAL get version fix
  msautotest/pymod/mstestlib.py
Labels: backport branch-8-4

#7345 Make projection context ref counting thread safe again (#7079)
  src/mapproject.c
Labels: backport branch-8-4

#7347 Update Ubuntu CI setup.sh
  ci/ubuntu/setup.sh
Labels: CI Testing

#7351 add bootstrap resources install option to CMake build summary
  CMakeLists.txt
Labels: OGCAPI: Features

#7333 Fix use-after-free error in msDrawRasterLayerLowOpenDataset
  msautotest/wxs/wms_raster.map
  src/mapraster.c
Labels: backport branch-8-4

#7334 Fix(parser): Prevent crash with non-existent layer in REQUIRES
  msautotest/query/context.map
  msautotest/query/expected/context_test004.png
  msautotest/query/expected/context_test005.png
  src/maputil.c
Labels: backport branch-8-4
